[default]
region = 'us-east-1'

[haiku-3]
model = 'anthropic.claude-3-haiku-20240307-v1:0'

[haiku-3-5]
model = 'us.anthropic.claude-3-5-haiku-20241022-v1:0'

[sonnet-3]
model = 'anthropic.claude-3-sonnet-20240229-v1:0'

[sonnet-3-5]
model = 'us.anthropic.claude-3-5-sonnet-20241022-v2:0'

[nova-lite]
model = 'amazon.nova-lite-v1:0'

[qwen2-1-5B]
model = 'artifacts/Qwen2-1.5B'

[phi3-8B]
model = 'artifacts/Phi3-8B'