[default]
region = 'us-east-1'

[haiku-3]
model = 'anthropic.claude-3-haiku-20240307-v1:0'

[haiku-3-5]
model = 'us.anthropic.claude-3-5-haiku-20241022-v1:0'

[sonnet-3]
model = 'anthropic.claude-3-sonnet-20240229-v1:0'

[sonnet-3-5]
model = 'us.anthropic.claude-3-5-sonnet-20241022-v2:0'

[nova-lite]
model = 'amazon.nova-lite-v1:0'

[haiku-3-5-cross]
model = "arn:aws:bedrock:us-east-1:{aws_account}:inference-profile/us.anthropic.claude-3-5-haiku-20241022-v1:0"

[phi-3-5-4B]
model = "Phi-3-5-mini-instruct"
hf_name = "microsoft/Phi-3.5-mini-instruct"

[qwen-2-5-1-5B]
model = "Qwen2-5-1-5B-Instruct"
hf_name = "Qwen/Qwen2.5-1.5B-Instruct"

